/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AthandleRouteImport } from './routes/[@]$handle'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthandleIndexRouteImport } from './routes/[@]$handle.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AthandleStuffRouteImport } from './routes/[@]$handle.stuff'
import { Route as AthandleFramesRouteImport } from './routes/[@]$handle.frames'
import { Route as AthandleDailyRouteImport } from './routes/[@]$handle.daily'
import { Route as AthandleCollectionsRouteImport } from './routes/[@]$handle.collections'
import { Route as AthandleAboutRouteImport } from './routes/[@]$handle.about'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AthandleRoute = AthandleRouteImport.update({
  id: '/@$handle',
  path: '/@$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthandleIndexRoute = AthandleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AthandleRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AthandleStuffRoute = AthandleStuffRouteImport.update({
  id: '/stuff',
  path: '/stuff',
  getParentRoute: () => AthandleRoute,
} as any)
const AthandleFramesRoute = AthandleFramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => AthandleRoute,
} as any)
const AthandleDailyRoute = AthandleDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AthandleRoute,
} as any)
const AthandleCollectionsRoute = AthandleCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AthandleRoute,
} as any)
const AthandleAboutRoute = AthandleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AthandleRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@$handle': typeof AthandleRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/@$handle/about': typeof AthandleAboutRoute
  '/@$handle/collections': typeof AthandleCollectionsRoute
  '/@$handle/daily': typeof AthandleDailyRoute
  '/@$handle/frames': typeof AthandleFramesRoute
  '/@$handle/stuff': typeof AthandleStuffRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/c/$id': typeof CIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/@$handle/': typeof AthandleIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/@$handle/about': typeof AthandleAboutRoute
  '/@$handle/collections': typeof AthandleCollectionsRoute
  '/@$handle/daily': typeof AthandleDailyRoute
  '/@$handle/frames': typeof AthandleFramesRoute
  '/@$handle/stuff': typeof AthandleStuffRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/c/$id': typeof CIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/@$handle': typeof AthandleIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/@$handle': typeof AthandleRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/@$handle/about': typeof AthandleAboutRoute
  '/@$handle/collections': typeof AthandleCollectionsRoute
  '/@$handle/daily': typeof AthandleDailyRoute
  '/@$handle/frames': typeof AthandleFramesRoute
  '/@$handle/stuff': typeof AthandleStuffRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/c/$id': typeof CIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/@$handle/': typeof AthandleIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@$handle'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/@$handle/about'
    | '/@$handle/collections'
    | '/@$handle/daily'
    | '/@$handle/frames'
    | '/@$handle/stuff'
    | '/settings'
    | '/upload'
    | '/c/$id'
    | '/p/$id'
    | '/u/$username'
    | '/@$handle/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/@$handle/about'
    | '/@$handle/collections'
    | '/@$handle/daily'
    | '/@$handle/frames'
    | '/@$handle/stuff'
    | '/settings'
    | '/upload'
    | '/c/$id'
    | '/p/$id'
    | '/u/$username'
    | '/@$handle'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/@$handle'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/@$handle/about'
    | '/@$handle/collections'
    | '/@$handle/daily'
    | '/@$handle/frames'
    | '/@$handle/stuff'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/c/$id'
    | '/p/$id'
    | '/u/$username'
    | '/@$handle/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AthandleRoute: typeof AthandleRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CIdRoute: typeof CIdRoute
  PIdRoute: typeof PIdRoute
  UUsernameRoute: typeof UUsernameRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@$handle': {
      id: '/@$handle'
      path: '/@$handle'
      fullPath: '/@$handle'
      preLoaderRoute: typeof AthandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@$handle/': {
      id: '/@$handle/'
      path: '/'
      fullPath: '/@$handle/'
      preLoaderRoute: typeof AthandleIndexRouteImport
      parentRoute: typeof AthandleRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/@$handle/stuff': {
      id: '/@$handle/stuff'
      path: '/stuff'
      fullPath: '/@$handle/stuff'
      preLoaderRoute: typeof AthandleStuffRouteImport
      parentRoute: typeof AthandleRoute
    }
    '/@$handle/frames': {
      id: '/@$handle/frames'
      path: '/frames'
      fullPath: '/@$handle/frames'
      preLoaderRoute: typeof AthandleFramesRouteImport
      parentRoute: typeof AthandleRoute
    }
    '/@$handle/daily': {
      id: '/@$handle/daily'
      path: '/daily'
      fullPath: '/@$handle/daily'
      preLoaderRoute: typeof AthandleDailyRouteImport
      parentRoute: typeof AthandleRoute
    }
    '/@$handle/collections': {
      id: '/@$handle/collections'
      path: '/collections'
      fullPath: '/@$handle/collections'
      preLoaderRoute: typeof AthandleCollectionsRouteImport
      parentRoute: typeof AthandleRoute
    }
    '/@$handle/about': {
      id: '/@$handle/about'
      path: '/about'
      fullPath: '/@$handle/about'
      preLoaderRoute: typeof AthandleAboutRouteImport
      parentRoute: typeof AthandleRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AthandleRouteChildren {
  AthandleAboutRoute: typeof AthandleAboutRoute
  AthandleCollectionsRoute: typeof AthandleCollectionsRoute
  AthandleDailyRoute: typeof AthandleDailyRoute
  AthandleFramesRoute: typeof AthandleFramesRoute
  AthandleStuffRoute: typeof AthandleStuffRoute
  AthandleIndexRoute: typeof AthandleIndexRoute
}

const AthandleRouteChildren: AthandleRouteChildren = {
  AthandleAboutRoute: AthandleAboutRoute,
  AthandleCollectionsRoute: AthandleCollectionsRoute,
  AthandleDailyRoute: AthandleDailyRoute,
  AthandleFramesRoute: AthandleFramesRoute,
  AthandleStuffRoute: AthandleStuffRoute,
  AthandleIndexRoute: AthandleIndexRoute,
}

const AthandleRouteWithChildren = AthandleRoute._addFileChildren(
  AthandleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AthandleRoute: AthandleRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CIdRoute: CIdRoute,
  PIdRoute: PIdRoute,
  UUsernameRoute: UUsernameRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
