/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as GHandleRouteImport } from './routes/g.$handle'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as GHandleIndexRouteImport } from './routes/g.$handle.index'
import { Route as GHandleStuffRouteImport } from './routes/g.$handle.stuff'
import { Route as GHandleFramesRouteImport } from './routes/g.$handle.frames'
import { Route as GHandleDailyRouteImport } from './routes/g.$handle.daily'
import { Route as GHandleCollectionsRouteImport } from './routes/g.$handle.collections'
import { Route as GHandleAboutRouteImport } from './routes/g.$handle.about'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as GHandleFSlugRouteImport } from './routes/g.$handle.f.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GHandleRoute = GHandleRouteImport.update({
  id: '/g/$handle',
  path: '/g/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const GHandleIndexRoute = GHandleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GHandleRoute,
} as any)
const GHandleStuffRoute = GHandleStuffRouteImport.update({
  id: '/stuff',
  path: '/stuff',
  getParentRoute: () => GHandleRoute,
} as any)
const GHandleFramesRoute = GHandleFramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => GHandleRoute,
} as any)
const GHandleDailyRoute = GHandleDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => GHandleRoute,
} as any)
const GHandleCollectionsRoute = GHandleCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => GHandleRoute,
} as any)
const GHandleAboutRoute = GHandleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => GHandleRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const GHandleFSlugRoute = GHandleFSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => GHandleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/c/$id': typeof CIdRoute
  '/g/$handle': typeof GHandleRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/g/$handle/about': typeof GHandleAboutRoute
  '/g/$handle/collections': typeof GHandleCollectionsRoute
  '/g/$handle/daily': typeof GHandleDailyRoute
  '/g/$handle/frames': typeof GHandleFramesRoute
  '/g/$handle/stuff': typeof GHandleStuffRoute
  '/g/$handle/': typeof GHandleIndexRoute
  '/g/$handle/f/$slug': typeof GHandleFSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/c/$id': typeof CIdRoute
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/g/$handle/about': typeof GHandleAboutRoute
  '/g/$handle/collections': typeof GHandleCollectionsRoute
  '/g/$handle/daily': typeof GHandleDailyRoute
  '/g/$handle/frames': typeof GHandleFramesRoute
  '/g/$handle/stuff': typeof GHandleStuffRoute
  '/g/$handle': typeof GHandleIndexRoute
  '/g/$handle/f/$slug': typeof GHandleFSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/c/$id': typeof CIdRoute
  '/g/$handle': typeof GHandleRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/g/$handle/about': typeof GHandleAboutRoute
  '/g/$handle/collections': typeof GHandleCollectionsRoute
  '/g/$handle/daily': typeof GHandleDailyRoute
  '/g/$handle/frames': typeof GHandleFramesRoute
  '/g/$handle/stuff': typeof GHandleStuffRoute
  '/g/$handle/': typeof GHandleIndexRoute
  '/g/$handle/f/$slug': typeof GHandleFSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/settings'
    | '/upload'
    | '/c/$id'
    | '/g/$handle'
    | '/p/$id'
    | '/u/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/g/$handle/about'
    | '/g/$handle/collections'
    | '/g/$handle/daily'
    | '/g/$handle/frames'
    | '/g/$handle/stuff'
    | '/g/$handle/'
    | '/g/$handle/f/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/settings'
    | '/upload'
    | '/c/$id'
    | '/p/$id'
    | '/u/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/g/$handle/about'
    | '/g/$handle/collections'
    | '/g/$handle/daily'
    | '/g/$handle/frames'
    | '/g/$handle/stuff'
    | '/g/$handle'
    | '/g/$handle/f/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/c/$id'
    | '/g/$handle'
    | '/p/$id'
    | '/u/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/g/$handle/about'
    | '/g/$handle/collections'
    | '/g/$handle/daily'
    | '/g/$handle/frames'
    | '/g/$handle/stuff'
    | '/g/$handle/'
    | '/g/$handle/f/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CIdRoute: typeof CIdRoute
  GHandleRoute: typeof GHandleRouteWithChildren
  PIdRoute: typeof PIdRoute
  UUsernameRoute: typeof UUsernameRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$handle': {
      id: '/g/$handle'
      path: '/g/$handle'
      fullPath: '/g/$handle'
      preLoaderRoute: typeof GHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$handle/': {
      id: '/g/$handle/'
      path: '/'
      fullPath: '/g/$handle/'
      preLoaderRoute: typeof GHandleIndexRouteImport
      parentRoute: typeof GHandleRoute
    }
    '/g/$handle/stuff': {
      id: '/g/$handle/stuff'
      path: '/stuff'
      fullPath: '/g/$handle/stuff'
      preLoaderRoute: typeof GHandleStuffRouteImport
      parentRoute: typeof GHandleRoute
    }
    '/g/$handle/frames': {
      id: '/g/$handle/frames'
      path: '/frames'
      fullPath: '/g/$handle/frames'
      preLoaderRoute: typeof GHandleFramesRouteImport
      parentRoute: typeof GHandleRoute
    }
    '/g/$handle/daily': {
      id: '/g/$handle/daily'
      path: '/daily'
      fullPath: '/g/$handle/daily'
      preLoaderRoute: typeof GHandleDailyRouteImport
      parentRoute: typeof GHandleRoute
    }
    '/g/$handle/collections': {
      id: '/g/$handle/collections'
      path: '/collections'
      fullPath: '/g/$handle/collections'
      preLoaderRoute: typeof GHandleCollectionsRouteImport
      parentRoute: typeof GHandleRoute
    }
    '/g/$handle/about': {
      id: '/g/$handle/about'
      path: '/about'
      fullPath: '/g/$handle/about'
      preLoaderRoute: typeof GHandleAboutRouteImport
      parentRoute: typeof GHandleRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$handle/f/$slug': {
      id: '/g/$handle/f/$slug'
      path: '/f/$slug'
      fullPath: '/g/$handle/f/$slug'
      preLoaderRoute: typeof GHandleFSlugRouteImport
      parentRoute: typeof GHandleRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GHandleRouteChildren {
  GHandleAboutRoute: typeof GHandleAboutRoute
  GHandleCollectionsRoute: typeof GHandleCollectionsRoute
  GHandleDailyRoute: typeof GHandleDailyRoute
  GHandleFramesRoute: typeof GHandleFramesRoute
  GHandleStuffRoute: typeof GHandleStuffRoute
  GHandleIndexRoute: typeof GHandleIndexRoute
  GHandleFSlugRoute: typeof GHandleFSlugRoute
}

const GHandleRouteChildren: GHandleRouteChildren = {
  GHandleAboutRoute: GHandleAboutRoute,
  GHandleCollectionsRoute: GHandleCollectionsRoute,
  GHandleDailyRoute: GHandleDailyRoute,
  GHandleFramesRoute: GHandleFramesRoute,
  GHandleStuffRoute: GHandleStuffRoute,
  GHandleIndexRoute: GHandleIndexRoute,
  GHandleFSlugRoute: GHandleFSlugRoute,
}

const GHandleRouteWithChildren =
  GHandleRoute._addFileChildren(GHandleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CIdRoute: CIdRoute,
  GHandleRoute: GHandleRouteWithChildren,
  PIdRoute: PIdRoute,
  UUsernameRoute: UUsernameRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
